### ISSUE TITLE
tombo resquiggle crashes, ont-vbz-hdf-plugin did not help

### ISSUE THREAD

**Issue by HeLi-80** [PengNi/deepsignal-plant#25]
Hi,
I'm having trouble with tombo resquiggle using my fast5s. Everything is fine up to tombo preprocess, but then tombo resquiggle crashes. I added ont-vbz-hdf-plugin to my environment but nothing changed.
Here is the result of tombo resquiggle:

[17:39:37] Loading minimap2 reference.
[17:39:55] Getting file list.
[17:39:55] Loading default canonical ***** DNA ***** model.
[17:39:55] Re-squiggling reads (raw signal to genomic sequence alignment).
  0%|                                                                                            | 0/10 [00:00<?, ?it/s]Exception in thread Thread-1 (_io_and_mappy_thread_worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1662, in _io_and_mappy_thread_worker
    _io_and_map_read(
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1395, in _io_and_map_read
    all_raw_signal = th.get_raw_read_slot(fast5_data)['Signal'][:]
  File "h5py/_debian_h5py_serial/_objects.pyx", line 54, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "h5py/_debian_h5py_serial/_objects.pyx", line 55, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/_hl/dataset.py", line 710, in __getitem__
    return self._fast_reader.read(args)
  File "h5py/_debian_h5py_serial/_selector.pyx", line 366, in h5py._debian_h5py_serial._selector.Reader.read
OSError: Can't read data (can't open directory: /usr/lib/x86_64-linux-gnu/hdf5/serial/plugins)
Exception in thread Thread-3 (_io_and_mappy_thread_worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
Exception in thread Thread-5 (_io_and_mappy_thread_worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1662, in _io_and_mappy_thread_worker
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    _io_and_map_read(
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1395, in _io_and_map_read
    self._target(*self._args, **self._kwargs)
    all_raw_signal = th.get_raw_read_slot(fast5_data)['Signal'][:]
  File "h5py/_debian_h5py_serial/_objects.pyx", line 54, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1662, in _io_and_mappy_thread_worker
    _io_and_map_read(
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1395, in _io_and_map_read
  File "h5py/_debian_h5py_serial/_objects.pyx", line 55, in h5py._debian_h5py_serial._objects.with_phil.wrapper
    all_raw_signal = th.get_raw_read_slot(fast5_data)['Signal'][:]
  File "h5py/_debian_h5py_serial/_objects.pyx", line 54, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/_hl/dataset.py", line 710, in __getitem__
  File "h5py/_debian_h5py_serial/_objects.pyx", line 55, in h5py._debian_h5py_serial._objects.with_phil.wrapper
    return self._fast_reader.read(args)
  File "h5py/_debian_h5py_serial/_selector.pyx", line 366, in h5py._debian_h5py_serial._selector.Reader.read
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/_hl/dataset.py", line 710, in __getitem__
OSError: Can't read data (can't open directory: /usr/lib/x86_64-linux-gnu/hdf5/serial/plugins)
    return self._fast_reader.read(args)
  File "h5py/_debian_h5py_serial/_selector.pyx", line 366, in h5py._debian_h5py_serial._selector.Reader.read
OSError: Can't read data (can't open directory: /usr/lib/x86_64-linux-gnu/hdf5/serial/plugins)
Exception in thread Thread-7 (_io_and_mappy_thread_worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1662, in _io_and_mappy_thread_worker
    _io_and_map_read(
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1395, in _io_and_map_read
    all_raw_signal = th.get_raw_read_slot(fast5_data)['Signal'][:]
  File "h5py/_debian_h5py_serial/_objects.pyx", line 54, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "h5py/_debian_h5py_serial/_objects.pyx", line 55, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/_hl/dataset.py", line 710, in __getitem__
    return self._fast_reader.read(args)
  File "h5py/_debian_h5py_serial/_selector.pyx", line 366, in h5py._debian_h5py_serial._selector.Reader.read
OSError: Can't read data (can't open directory: /usr/lib/x86_64-linux-gnu/hdf5/serial/plugins)
Exception in thread Thread-8 (_io_and_mappy_thread_worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1662, in _io_and_mappy_thread_worker
    _io_and_map_read(
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1395, in _io_and_map_read
    all_raw_signal = th.get_raw_read_slot(fast5_data)['Signal'][:]
  File "h5py/_debian_h5py_serial/_objects.pyx", line 54, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "h5py/_debian_h5py_serial/_objects.pyx", line 55, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/_hl/dataset.py", line 710, in __getitem__
    return self._fast_reader.read(args)
  File "h5py/_debian_h5py_serial/_selector.pyx", line 366, in h5py._debian_h5py_serial._selector.Reader.read
OSError: Can't read data (can't open directory: /usr/lib/x86_64-linux-gnu/hdf5/serial/plugins)
Exception in thread Thread-10 (_io_and_mappy_thread_worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1662, in _io_and_mappy_thread_worker
    _io_and_map_read(
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1395, in _io_and_map_read
    all_raw_signal = th.get_raw_read_slot(fast5_data)['Signal'][:]
  File "h5py/_debian_h5py_serial/_objects.pyx", line 54, in h5py._debian_h5py_serial._objects.with_phil.wrapper
Exception in thread Thread-9 (_io_and_mappy_thread_worker):
Traceback (most recent call last):
  File "h5py/_debian_h5py_serial/_objects.pyx", line 55, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/_hl/dataset.py", line 710, in __getitem__
    self._target(*self._args, **self._kwargs)
    return self._fast_reader.read(args)
  File "h5py/_debian_h5py_serial/_selector.pyx", line 366, in h5py._debian_h5py_serial._selector.Reader.read
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1662, in _io_and_mappy_thread_worker
OSError: Can't read data (can't open directory: /usr/lib/x86_64-linux-gnu/hdf5/serial/plugins)
    _io_and_map_read(
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1395, in _io_and_map_read
    all_raw_signal = th.get_raw_read_slot(fast5_data)['Signal'][:]
  File "h5py/_debian_h5py_serial/_objects.pyx", line 54, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "h5py/_debian_h5py_serial/_objects.pyx", line 55, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/_hl/dataset.py", line 710, in __getitem__
    return self._fast_reader.read(args)
  File "h5py/_debian_h5py_serial/_selector.pyx", line 366, in h5py._debian_h5py_serial._selector.Reader.read
OSError: Can't read data (can't open directory: /usr/lib/x86_64-linux-gnu/hdf5/serial/plugins)
Exception in thread Thread-2 (_io_and_mappy_thread_worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1662, in _io_and_mappy_thread_worker
    _io_and_map_read(
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1395, in _io_and_map_read
    all_raw_signal = th.get_raw_read_slot(fast5_data)['Signal'][:]
  File "h5py/_debian_h5py_serial/_objects.pyx", line 54, in h5py._debian_h5py_serial._objects.with_phil.wrapper
Exception in thread Thread-4 (_io_and_mappy_thread_worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "h5py/_debian_h5py_serial/_objects.pyx", line 55, in h5py._debian_h5py_serial._objects.with_phil.wrapper
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/_hl/dataset.py", line 710, in __getitem__
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1662, in _io_and_mappy_thread_worker
    return self._fast_reader.read(args)
    _io_and_map_read(
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1395, in _io_and_map_read
  File "h5py/_debian_h5py_serial/_selector.pyx", line 366, in h5py._debian_h5py_serial._selector.Reader.read
Exception in thread Thread-6 (_io_and_mappy_thread_worker):
    all_raw_signal = th.get_raw_read_slot(fast5_data)['Signal'][:]
  File "h5py/_debian_h5py_serial/_objects.pyx", line 54, in h5py._debian_h5py_serial._objects.with_phil.wrapper
OSError: Can't read data (can't open directory: /usr/lib/x86_64-linux-gnu/hdf5/serial/plugins)
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
  File "h5py/_debian_h5py_serial/_objects.pyx", line 55, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/_hl/dataset.py", line 710, in __getitem__
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1662, in _io_and_mappy_thread_worker
    return self._fast_reader.read(args)
  File "h5py/_debian_h5py_serial/_selector.pyx", line 366, in h5py._debian_h5py_serial._selector.Reader.read
    _io_and_map_read(
  File "/usr/lib/python3/dist-packages/tombo/resquiggle.py", line 1395, in _io_and_map_read
OSError: Can't read data (can't open directory: /usr/lib/x86_64-linux-gnu/hdf5/serial/plugins)
    all_raw_signal = th.get_raw_read_slot(fast5_data)['Signal'][:]
  File "h5py/_debian_h5py_serial/_objects.pyx", line 54, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "h5py/_debian_h5py_serial/_objects.pyx", line 55, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/_hl/dataset.py", line 710, in __getitem__
    return self._fast_reader.read(args)
  File "h5py/_debian_h5py_serial/_selector.pyx", line 366, in h5py._debian_h5py_serial._selector.Reader.read
OSError: Can't read data (can't open directory: /usr/lib/x86_64-linux-gnu/hdf5/serial/plugins)

Thank you

**Comment by PengNi** [comment]
Hi @HeLi-80 , it seems the plugin wasn't imported correctly, Tombo still had to find plugin in `/usr/lib/x86_64-linux-gnu/hdf5/serial/plugins`.

What was the command you used to export the path of the vbz-plugin?

Best,
Peng

**Comment by HeLi-80** [comment]
Hi @PengNi, thank you for your prompt reply. Problem solved: I didn't export the correct path of the vbz-plugin. With the right path, resquiggle works fine. 
Best,
Elio
